import { Cite, Equation } from '@fasl-work/caos-app-shell';
import type { RiemannShortWindowMoment } from '../api/data';
import { useT } from '../lib/i18n';

const EXP = 'https://github.com/fsantibanezleal/CAOS_RESEARCH/blob/main/problems/number-theory/riemann-hypothesis/experiments/EXP-028-chirp-separated-moment/';
const DOI = 'https://doi.org/10.5281/zenodo.22984154';
export default function RiemannMoment({ evidence, mode }: {
  evidence: RiemannShortWindowMoment | null;
  mode: 'summary' | 'context' | 'approaches' | 'strategy' | 'results' | 'open';
}) {
  const t = useT();
  if (!evidence) return <p role="status" className="rh-moment-unavailable">{t('The reviewed short-window moment evidence is unavailable in this replay.', 'La evidencia revisada del momento en ventanas cortas no está disponible en esta reproducción.')} <a href={DOI} target="_blank" rel="noreferrer">{t('Published manuscript', 'Manuscrito publicado')}</a></p>;
  const m = evidence;
  return <section className="rh-moment" data-evidence="EXP-028">
    <h2>{t('Longer short-window mollifier', 'Mollificador más largo en ventanas cortas')}</h2>
    {mode === 'summary' && <>
      <p className="rh-lead">{t('EXP-028 extends the admissible mollifier length. With the fixed certified detector and Wang’s pair theorem, every fixed θ in [0.5339, 1) has a positive asymptotic proportion of simple critical-line zeros in (T, T + T^θ]. The earlier onset was 0.534.', 'EXP-028 amplía la longitud admisible del mollificador. Con el detector certificado fijo y el teorema de pares de Wang, cada θ fijo en [0.5339, 1) tiene una proporción asintótica positiva de ceros simples en la recta crítica en (T, T + T^θ]. El umbral anterior era 0.534.')}</p>
      <Equation tex={String.raw`0<\nu<\min\!\left(\frac12,\frac{17}{33}(2\theta-1)\right),\qquad \frac12<\theta<1`} />
      <p className="rh-number">{t('Simple-critical density at θ = 0.5339 exceeds ', 'La densidad de ceros críticos simples en θ = 0.5339 supera ')}<strong>{m.simple_density_decimal}</strong>.</p>
    </>}
    {mode === 'context' && <p>{t('EXP-010 localized Levinson’s method with ν < θ − 1/2. EXP-028 replaces its elementary absolute off-diagonal estimate by Bettin-Chandee’s trilinear bound after exact coefficient separation. The numerical onset improves by 0.0001; the substantive result is the uniform moment range, larger by a factor 34/33 before the ν < 1/2 cap. The detector is unchanged.', 'EXP-010 localizó el método de Levinson con ν < θ − 1/2. EXP-028 reemplaza su estimación absoluta elemental fuera de la diagonal por la cota trilineal de Bettin-Chandee tras separar exactamente los coeficientes. El umbral numérico mejora en 0.0001; el resultado sustantivo es el rango uniforme del momento, mayor por un factor 34/33 antes de la restricción ν < 1/2. El detector no cambia.')} <Cite id="riemann-bettinchandee2015" /></p>}
    {mode === 'approaches' && <>
      <p>{t('The signed Gaussian representation and shifted composite Voronoi formula keep the original arithmetic coefficients. In Mellin coordinates, (pq/n)^it separates into p^it q^it n^−it. The absolute gamma-multiplier norm is charged before applying the trilinear theorem. Moving a separate contour for each finite dual block controls the entire tail. An exact Hankel integral provides an independent derivation of the same separation cost.', 'La representación gaussiana con signo y la fórmula de Voronoi compuesta y desplazada conservan los coeficientes aritméticos originales. En coordenadas de Mellin, (pq/n)^it se separa en p^it q^it n^−it. La norma absoluta del multiplicador gamma se contabiliza antes de aplicar el teorema trilineal. Mover un contorno separado para cada bloque dual finito controla toda la cola. Una integral exacta de Hankel ofrece una derivación independiente del mismo costo de separación.')}</p>
      <Equation tex={String.raw`(pq/n)^{it}=p^{it}q^{it}n^{-it}`} />
    </>}
    {mode === 'strategy' && <p>{t('The admitted target was a complete signed moment estimate, rather than another finite kernel sweep. Both residues and their coalescence, unbalanced blocks, gcd sums and fixed general operator polynomials are reviewed. Compact-window conversion uses a narrower Gaussian θ − η with η = 1/100000; both charged error exponents remain negative. EXP-023 stopped incomplete at its six-hour budget and is excluded.', 'El objetivo admitido era una estimación completa del momento con signo, en lugar de otro barrido finito de núcleos. Se revisaron ambos residuos y su coalescencia, los bloques desequilibrados, las sumas por máximo común divisor y los polinomios operadores generales fijos. La conversión a ventanas compactas usa una gaussiana más estrecha θ − η con η = 1/100000; ambos exponentes de error contabilizados siguen negativos. EXP-023 se detuvo incompleto al cumplir su presupuesto de seis horas y se excluye.')}</p>}
    {mode === 'results' && <>
      <p>{t('The complete analytic review is separate from historical conditional arithmetic receipts. Native and independent rational interval controls certify the endpoint density using the frozen EXP-010 detector. Exact rational checks cover 7,430 dyadic configurations and reject five incorrect alternatives. The extracted 80-member source archive replays all three EXP-028 auditors; both public downloads match the reviewed bytes.', 'La revisión analítica completa es independiente de los comprobantes históricos de aritmética condicional. Los controles de intervalos nativos y racionales independientes certifican la densidad del extremo usando el detector fijo de EXP-010. Las verificaciones racionales exactas abarcan 7.430 configuraciones diádicas y rechazan cinco alternativas incorrectas. El archivo extraído de 80 entradas reproduce los tres auditores de EXP-028; ambas descargas públicas coinciden con los bytes revisados.')}</p>
      <Equation tex={String.raw`E_1=-\frac{7}{250000}<0,\qquad E_2=-\frac{937}{400000}<0`} />
    </>}
    {mode === 'open' && <p>{t('An external specialist review and a broader prior-art comparison remain open. The theorem depends on Bettin-Chandee, Young and Wang’s recent pair-correlation preprint. Very large fixed smoothing orders and detector constants give no effective starting height. Further lengthening must improve the signed trilinear estimate or its separation cost; the failed multiplicity-defect route in EXP-026 supplies no universal positive extra remainder.', 'Siguen pendientes una revisión externa especializada y una comparación más amplia con trabajos previos. El teorema depende de Bettin-Chandee, Young y el reciente preprint de correlación de pares de Wang. Los órdenes fijos muy grandes de suavizado y las constantes del detector no dan una altura inicial efectiva. Un alargamiento adicional debe mejorar la estimación trilineal con signo o su costo de separación; la vía fallida del defecto de multiplicidad en EXP-026 no aporta un resto adicional positivo universal.')}</p>}
    <p className="small">{t('Internally reviewed and published. Arithmetic checks do not prove the analytic theorem. External peer review and worldwide priority are unconfirmed. RH remains open.', 'Revisado internamente y publicado. Las verificaciones aritméticas no prueban el teorema analítico. La revisión externa por pares y la prioridad mundial no están confirmadas. RH sigue abierta.')} <Cite id="riemann-levinson2026" /></p>
    <div className="rh-source-links"><a href={DOI} target="_blank" rel="noreferrer">{t('Manuscript v0.02 and source archive', 'Manuscrito v0.02 y archivo de fuentes')}</a><a href={`${EXP}mellin-proof.md`} target="_blank" rel="noreferrer">{t('Mellin proof', 'Prueba de Mellin')}</a><a href={`${EXP}hankel-symbol-proof.md`} target="_blank" rel="noreferrer">{t('Exact Hankel proof', 'Prueba exacta de Hankel')}</a><a href={`${EXP}verdict.md`} target="_blank" rel="noreferrer">{t('Verdict and limits', 'Veredicto y límites')}</a></div>
  </section>;
}
