"""Every headline number quoted in prose must still be in the artifact it came from.

Verdicts and wiki pages quote numbers from result JSONs and from code. Those files are
edited by hand and the results are regenerated by runs, so the two drift silently: a rerun
moves a value, the prose keeps the old one, and the old one is what a reader quotes. This
guard pins the numbers that carry the conclusions of EXP-005 and of the smoothness-versus-
dissipation trade-off to their sources.

It deliberately checks the FORMATTED strings that appear in the prose, not just the values,
because the failure mode is prose that no longer matches, not arithmetic that stopped
working.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PROBLEM = ROOT / "problems/analysis-pde/navier-stokes"
EXP005 = PROBLEM / "experiments/EXP-005-steered-cycle"
CODE = PROBLEM / "code"
if str(CODE) not in sys.path:
    sys.path.insert(0, str(CODE))


def load(name: str) -> dict:
    return json.loads((EXP005 / name).read_text(encoding="utf-8"))


def text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def test_exp005_part_b_numbers_match_the_flattened_run():
    d = load("result-B-flattened.json")
    m = d["main"]
    verdict = text(EXP005 / "verdict.md")

    assert m["landing_pde"] == pytest.approx(3.67e-4, rel=5e-3)
    assert m["gain_relative_error"] == pytest.approx(3.06e-6, rel=5e-3)
    assert m["hold_theta_relative_drift"] == pytest.approx(0.0036, rel=5e-2)
    assert d["endpoint_max_gap"] == pytest.approx(4.7e-4, rel=5e-2)
    assert d["all_pass"] is True

    for quoted in ("3.67e-04", "3.06e-06", "0.36 %", "4.7e-04"):
        assert quoted in verdict, f"{quoted} no longer appears in the verdict"


def test_exp005_part_b_sine_column_is_the_curvature_comparison():
    sine = load("result-B-sine.json")["main"]
    flat = load("result-B-flattened.json")["main"]
    # the whole point of the pair: same everything, worse only through curvature
    assert sine["landing_pde"] > 10 * flat["landing_pde"]
    assert sine["gain_relative_error"] > 100 * flat["gain_relative_error"]
    assert sine["landing_pde"] == pytest.approx(1.57e-2, rel=5e-2)
    assert "1.57e-02" in text(EXP005 / "verdict.md")


def test_exp005_part_c_factorization_numbers():
    d = load("result-C-dissipative.json")
    verdict = text(EXP005 / "verdict.md")
    assert d["viscous"]["landing_pde"] == pytest.approx(4.1e-4, rel=5e-2)
    assert d["hold_decay_rate_relative_error"] == pytest.approx(0.0097, rel=5e-2)
    assert d["factorization_worst_relative_error"] == pytest.approx(0.0024, rel=5e-2)
    assert d["all_pass"] is True
    for quoted in ("4.1e-04", "0.97 %", "0.24 %"):
        assert quoted in verdict


def test_exp005_part_d_numbers_and_the_gate_reported_as_not_met():
    d = load("result-D-handoff.json")
    verdict = text(EXP005 / "verdict.md")
    assert d["H1_total_gradient"]["corr"] == pytest.approx(0.808, abs=5e-3)
    assert d["H2_control_base_only"]["corr"] == pytest.approx(0.392, abs=5e-3)
    assert d["stage1"]["deposit_over_A0"] == pytest.approx(0.92, abs=5e-3)
    assert d["gates"]["D1_pattern"] is False           # and it must stay reported as such
    assert d["gates"]["D2_control_discriminates"] is True
    assert "0.808" in verdict and "0.392" in verdict
    assert "NOT met" in verdict


def test_the_refuted_run_keeps_its_note_and_its_failing_gates():
    d = load("result-B-committed-parameters-REFUTED.json")
    assert all(v is False for v in d["gates"].values())
    assert "Rayleigh-Taylor" in d["_note"]
    assert "REFUTED" in text(EXP005 / "verdict.md")


def test_wiki_page_8_numbers_come_from_the_code():
    from nslib import ab_schedule as A
    from nslib import cascade as C

    page = text(PROBLEM / "wiki/08-smoothness-versus-dissipation.md")
    s = A.ABSchedule()
    assert s.alpha_max(1) == pytest.approx(1.55e-4, rel=5e-3)
    assert s.alpha_max(2, favourable_angle=False) == pytest.approx(7.70e-7, rel=5e-3)
    assert s.stall_stage(1e-4) == 113
    assert A.ratio_needed_for(C.ALPHA0_CMZ / 2.0) == pytest.approx(0.675, abs=5e-3)
    assert A.derivatives_affordable(C.ALPHA0_CMZ / 2.0) == pytest.approx(0.006, abs=5e-4)

    for quoted in ("1.55\\times10^{-4}", "7.70\\times10^{-7}", "113", "0.675", "0.006"):
        assert quoted in page, f"{quoted} no longer appears in wiki page 8"


def test_wiki_page_6_ratio_interval_numbers_come_from_the_code():
    from nslib import cmz_budget as B

    page = text(PROBLEM / "wiki/06-where-the-published-threshold-comes-from.md")
    lo, hi = B.feasible_R_interval(0.05)
    assert lo == pytest.approx(1.143, abs=5e-4) and hi == pytest.approx(5.0, abs=5e-3)
    assert B.feasible_R_interval(0.10) is None
    closed = B.feasible_R_interval(B.ALPHA0)
    assert closed[1] - closed[0] < 1e-6
    assert closed[0] == pytest.approx(1.7559, abs=5e-4)

    for quoted in ("1.143", "5.000", "1.7559", "empty"):
        assert quoted in page, f"{quoted} no longer appears in wiki page 6"


def test_the_converse_bound_numbers_match_the_code():
    """The sharpened claim: one derivative caps the exponent at 1/480."""
    from nslib import ab_schedule as A

    page = text(PROBLEM / "wiki/08-smoothness-versus-dissipation.md")
    dossier = text(PROBLEM / "context/2026-09-16-smoothness-versus-dissipation.md")

    assert A.alpha_max_for_derivatives(1) == pytest.approx(1.0 / 480.0)
    assert A.gap_to_published_threshold(1, 1.0) == pytest.approx(22.2, rel=5e-2)
    assert A.gap_to_published_threshold(1, A.DELTA_PUBLISHED) == pytest.approx(177.9, rel=5e-2)

    for quoted in ("1/480=0.00208", "twenty-two times", "one hundred and seventy-eight"):
        assert quoted in page, f"{quoted} no longer appears in wiki page 8"
    for quoted in ("alpha < delta / (480 k)", "1/480 = 0.00208", "22 times", "178 times"):
        assert quoted in dossier, f"{quoted} no longer appears in the dossier"
