"""SUPERSEDED 2026-09-17 by `ab_force_budget`; kept unchanged below as the record of v0.04.

The inequality this module encodes, `J[(1 - delta) - 5/Q] >= k + 6`, misreads the primary
source in two places: the seed rule `lambda^(-k-6)` bounds the activation contribution, not
the remainder (whose target is `lambda^(-3/2)`, their (7.26)), and the per-level parameter is
`Pi^5 lambda^(-7/8) <= lambda^(-7/8 + 25/Q)`, not `lambda^(-7/8 + 5/Q)`. It also omits the
nonoscillatory phase means, which bind at the published choices. Its number, 1.08e-03 in the
`|grad|^alpha` convention, was published in v0.04 and is corrected in v0.05.

The ceiling of the Alpoge-Buckmaster mechanism under fractional dissipation.

This is the conclusion of the audit, not another observation about it: a single number
bounding what that published design can carry, derived from its own displayed constants.

THE THREE INGREDIENTS, all theirs except the last.

1. The correction hierarchy. Their Subsection 7.1.1 sets the per-level small parameter
   `Pi^5 lambda^(-7/8)`, where `lambda^(-7/8)` is exactly the amplitude bound `Y` of their
   Definition 7.1(iii). Writing the amplitude as `lambda^(-1+delta)` with their margin
   `delta = 1/8`, the per-level parameter is `Pi^5 lambda^(-(1-delta))`, and their
   `J = 2k + 8` levels gain that factor `J` times. Their (7.4) bounds `Pi <= lambda^(5/Q)`.

2. The force target. Their seed `Theta_seed = lambda^(-k-6)` is chosen, in their own words,
   "small enough that the force generated by smooth activation is within the required
   bound", so the target is `lambda^(-6)` after `k` derivatives, each costing `lambda` on a
   wave of frequency `lambda`. Hence

       J [ (1 - delta) - 5/Q ]  >=  k + 6.                                    (*)

3. The dissipation constraint, ours: a layer grows only while
   `nu lambda^(2 alpha) < sqrt(A) sin s`, which in their variables is
   `alpha < delta / (4 Q)` (see `ab_schedule`), derived from the modulation system and
   confirmed against the nonlinear equations by EXP-002, with the localization correction
   measured in EXP-007 and negligible at their separations.

THE CONSEQUENCE. (*) caps the margin, the margin caps the exponent, and their rule
`120 k <= Q` ties the ratio to the regularity. Maximizing over `k` gives

    alpha <= 5.382e-04   at k = 1, Q = 120, delta <= 0.2583,

in our `(-Laplacian)^alpha` convention, that is `1.076e-03` in theirs. For comparison,
blowup is already PROVED for every exponent below `0.0463` (ours) with a merely
`C^(1,eps)` force. **The smooth-forcing design is therefore about 86 times short of the
regime that is already reached with a rough force, and no retuning of its constants closes
that gap: the margin cannot exceed 1/2 however many derivatives are demanded, while the
ratio grows at least linearly in them.**

This is a statement about a design, not about a theorem: their published result is inviscid
and nothing here contradicts it.
"""

from __future__ import annotations

from dataclasses import dataclass

CORRECTION_LEVELS_BASE = 8      # their J = 2k + 8
CORRECTION_LEVELS_PER_DERIVATIVE = 2
SEED_SLACK = 6                  # their Theta_seed = lambda^(-k-6)
PI_EXPONENT = 5                 # their per-level parameter Pi^5 lambda^(-(1-delta))
PI_OVER_Q = 5                   # their (7.4): Pi <= lambda^(5/Q)
RATIO_PER_DERIVATIVE = 120      # their rule 120 k <= Q


@dataclass(frozen=True)
class Design:
    """A design of the mechanism: `k` derivatives controlled, frequency ratio `Q`."""

    k: int
    Q: float | None = None      # defaults to the smallest ratio their rule allows

    def __post_init__(self) -> None:
        if self.k < 1:
            raise ValueError("at least one derivative of the force must be controlled")

    @property
    def ratio(self) -> float:
        return float(self.Q) if self.Q is not None else float(RATIO_PER_DERIVATIVE * self.k)

    @property
    def levels(self) -> int:
        """`J = 2k + 8`, their number of correction levels."""
        return CORRECTION_LEVELS_PER_DERIVATIVE * self.k + CORRECTION_LEVELS_BASE

    @property
    def margin_max(self) -> float:
        """Largest amplitude margin `delta` the correction hierarchy permits, from (*)."""
        J, Q = self.levels, self.ratio
        return 1.0 - (self.k + SEED_SLACK) / J - PI_OVER_Q / Q

    @property
    def alpha_max(self) -> float:
        """Largest dissipation exponent this design can carry, `delta/(4 Q)`."""
        return max(0.0, self.margin_max) / (4.0 * self.ratio)


def ceiling(k_max: int = 2000) -> tuple[Design, float]:
    """The best design and its exponent: the mechanism's ceiling.

    The trade-off is visible in the two limits. Raising `k` relaxes the margin, since more
    correction levels gain more, but it raises the ratio at least linearly, and the ratio
    enters the exponent directly. The margin saturates at `1/2` while the ratio grows
    without bound, so the optimum sits at the smallest admissible regularity.
    """
    best = max((Design(k) for k in range(1, k_max + 1)), key=lambda d: d.alpha_max)
    return best, best.alpha_max


def margin_limit() -> float:
    """The margin's own ceiling as `k` grows: `1/2`.

    From (*) with `Q = 120k`: `delta <= 1 - (k+6)/(2k+8) - 1/(24k) -> 1/2`.
    """
    return 0.5


def in_their_convention(alpha_ours: float) -> float:
    """Convert our `(-Laplacian)^alpha` exponent to their `|grad|^alpha`."""
    return 2.0 * alpha_ours


def shortfall_against_proved(alpha_ours: float) -> float:
    """How many times below the proved rough-force threshold a design sits."""
    from . import cascade

    return (cascade.ALPHA0_CMZ / 2.0) / alpha_ours


def table(ks=(1, 2, 3, 5, 10, 50, 1000)) -> list[dict]:
    """The ceiling and its neighbourhood, for the record and for the paper."""
    rows = []
    for k in ks:
        d = Design(k)
        rows.append({
            "k": k,
            "levels": d.levels,
            "ratio": d.ratio,
            "margin_max": d.margin_max,
            "alpha_max_ours": d.alpha_max,
            "alpha_max_theirs": in_their_convention(d.alpha_max),
            "times_below_proved": shortfall_against_proved(d.alpha_max),
        })
    return rows


def equivalent_smoothness_at_the_proved_threshold() -> float:
    """How many derivatives this design could control at the proved threshold. Below one.

    Solving `delta/(4Q) = alpha_0/2` with the margin capped by (*) has no solution with
    `k >= 1`; the quantity returned is the formal `k` the ratio rule would allow, which is
    what makes the shortfall structural rather than a matter of constants.
    """
    from . import cascade

    alpha = cascade.ALPHA0_CMZ / 2.0
    return margin_limit() / (4.0 * alpha * RATIO_PER_DERIVATIVE)
